### PR TITLE
added a historical quote function to Quote

### PR DESCRIPTION
**Pull request by jacks821**
This only gives the closing price of the requested day.

### CODE REVIEW

**Comment by ackleymi** [comment]
@jacks821 looks pretty good. Thanks for taking this on, I've been busy with some other projects. Can you look into the failing checks? Also, for full integration tests, I suppose we'll need a modification to the test server project https://github.com/piquette/finance-mock (annoying I know). Let me know if you have any thoughts. Maybe a unit test will suffice?

**Comment by jacks821** [comment]
I appreciate the feedback!  I'm gonna do that and re up the commit!

**Comment by ackleymi** [comment]
@jacks821 and what is your thoughts on returning the day's OHLC values, instead of just the close?

**Comment by jacks821** [comment]
I like that idea a lot.  But I think i'd have to build it a little differently, unless you have an idea of how to do that using the Chart API?  I'll work on just doing it separately.

**Comment by ackleymi** [comment]
I'll work up an example and post it here in a bit

**Comment by jacks821** [comment]
I fixed it so that it returns the OHLC values as just a ChartBar.  I just wasn't understanding how the Iters worked.

**Comment by ackleymi** [comment]
@jacks821 this looks ok to merge. I'll tack on a follow up PR that adds gofmt shortcuts to the Makefile and make sure its listed in the requirements for subsequent PRs. I'll ping you that PR when I'm done to show you what I mean. :)

**Comment by jacks821** [comment]
I don't mean to push you, just wanted to see if you were gonna show me those shortcuts?  Also, i noticed you're from Ann Arbor.  I'm originally from Detroit, myself.

**Pull request merged**
